### ISSUE TITLE
Best model for seedling growth

### ISSUE THREAD

**Issue by hrlai** [wengngai/NSSF_habitatmismatch#1]
@wengngai is the best model for seedling growth `sg.HM`?

**Comment by hrlai** [comment]
Actually may I get the object names for the best model for survival, seedling growth, adult growth, fruiting incident, and fruiting volume?

**Comment by wengngai** [comment]
So sorry the Rdata files are a bit too large to upload, which is why the load() function still can't be used to obtain the whole list. I assume you're refitting only the best the models? I think instead of doing so maybe I'll just upload the Rdata of the best model. And edit the script so that it can be loaded in directly. Getting down to it now

**Comment by hrlai** [comment]
@wengngai no need to rush the model files, which are large and shouldn't be pushed unless absolutely necessary. Best to just let me know the object names (one for each vital rate) here :)

**Comment by wengngai** [comment]
actually I just finished doing it haha... the codes should now all run fine, and give you the best model at the end of the model selection section. for FI and FV, the whole model lists are in /Rdata, and you can also run the model selection process if you want to. for SG and AG, only the best model is uploaded, so you would have to skip to the end of the model selection section and just load that best model.
we're still running the survival models (they are EXTREMELY slow for some reason), so those won't be coming any time soon unfortunately

**Comment by hrlai** [comment]
thanks! will take a closer look
